### ISSUE TITLE
Can't download model Checkpoint 

### ISSUE THREAD

**Issue by hamzakhalil798** [ID56/Torch-KWT#8]
![image](https://user-images.githubusercontent.com/103629235/195044215-acb5993c-6394-4f90-99ea-1df546338724.png)

**Comment by mashrurmorshed** [comment]
Hi, the checkpoint was stored in the drive space with an organization email which is no longer active. I've uploaded the checkpoint again to my personal drive and updated the [ckpt link](https://drive.google.com/uc?id=1y91PsZrnBXlmVmcDi26lDnpl4PoC5tXi&export=download) in the README, you can check it now.

**Comment by hamzakhalil798** [comment]
@ID56 Thankyou so much!
